name: Deploy web to Hosting

on:
  push:
    branches:
    - main # Deploy saat push ke branch utama

jobs:
  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Create .env.production
      run: |
        cat <<EOF > .env.production
        VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}
        VITE_API_URL=${{ secrets.VITE_API_URL }}
        VITE_DISCORD_USER_ID=${{ secrets.VITE_DISCORD_USER_ID }}
        EOF
        cat .env.production

    # Pindahkan .env.production ke dist/
    - name: Move .env.production to dist
      run: mv .env.production dist/

    - name: Build Project
      run: npm run build

    # Cek apakah .env.production benar-benar ada di dist/
    - name: Check files in dist before upload
      run: ls -lah dist/

    - name: Deploy project via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/src/**
          **/tests/**
          **/*.md

    - name: Install Dependencies for Express.js
      run: |
        cd backend
        npm install

    - name: Upload Express.js via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_API }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: backend/
        exclude: |
          **/.git*
          **/node_modules/**
          **/README.md
          **/.env*
