name: Deploy portfolio to Hosting

on:
  push:
    branches:
    - main # Deploy saat push ke branch utama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: ${{ secrets.FTP_FOLDER }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/src/**
          **/tests/**
          **/*.md
