name: Deploy portfolio to Hosting

on:
  push:
    branches:
    - main # Deploy saat push ke branch utama

jobs:
  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Cache FTP Deploy State
      uses: actions/cache@v3
      with:
        path: .ftp-deploy-sync-state
        key: ftp-cache-${{ github.sha }}
        restore-keys: ftp-cache-

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: ${{ secrets.FTP_FOLDER }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/src/**
          **/tests/**
          **/*.md
