name: Deploy portfolio project to Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    name: Deploy Client Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env.production file
      run: |
        echo "VITE_DISCORD_USER_ID=${{ secrets.VITE_DISCORD_USER_ID }}" >> .env.production
        echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env.production
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.production
        echo "VITE_APP_NAME='Fahri Anggara'" >> .env.production
        echo "VITE_SSR=true" >> .env.production

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Upload the DIST Folder
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        server-dir: ${{ secrets.FTP_DIR_CLIENT }}

    - name: Upload the package.json & server.js
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DIR_CLIENT }}
        exclude: |
          **/*
          !package.json
          !server.js

  deploy-api:
    name: Deploy API Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd api
        npm install

    - name: Upload the Project API
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: api/
        server-dir: ${{ secrets.FTP_DIR_API }}
        exclude: |
          **/node_modules/**
          **/README.md
          **/.env*