name: Deploy portfolio to Hosting

on:
  push:
    branches:
    - main # Deploy saat push ke branch utama

jobs:
  deploy:
    name: Deploy to Hosting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Create a ENV file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        envkey_VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        envkey_VITE_API_URL: ${{ secrets.VITE_API_URL }}
        envkey_VITE_DISCORD_USER_ID: ${{ secrets.VITE_DISCORD_USER_ID }}
        file_name: .env.production

    - name: Deploy project via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/src/**
          **/tests/**
          **/*.md

    - name: Install Dependencies for Express.js
      run: |
        cd backend
        npm install

    - name: Upload Express.js via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME_API }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: backend/
        exclude: |
          **/.git*
          **/node_modules/**
          **/README.md
          **/.env*
